version: "3"

service:
  cron_scheduler:
    command: php scheduler.php
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1
    relay: pipes
    user: "nobody"

  cron_consumer:
    command: php consumer.php
    process_num: 4
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1
    relay: pipes
    user: "nobody"
